

name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      env:
          DOCKER_URL: ${{secrets.DOCKER_URL}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: sudo docker pull $DOCKER_URL/$DOCKER_USERNAME/alitanew/alita:latest
    - name: Delete Old docker container
      run: sudo docker rm -f alita-container || true
    - name: Run Docker Container
      env:
          DOCKER_URL: ${{secrets.DOCKER_URL}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: sudo docker run -d --name alita-container $DOCKER_URL/$DOCKER_USERNAME/alitanew/alita
