name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Client
      run: sudo apt-get install openssh-client

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_HOST: ${{secrets.SSH_HOST}}
        SSH_USER: ${{secrets.SSH_USER}}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts

    - name: SSH and create directory
      env:
        SSH_HOST: ${{secrets.SSH_HOST}}
        SSH_USER: ${{secrets.SSH_USER}}
      run: ssh $SSH_USER@$SSH_HOST 'mkdir -p /home/ubuntu/deployments'

    - name: Pull Docker image
      env:
        SSH_HOST: ${{secrets.SSH_HOST}}
        SSH_USER: ${{secrets.SSH_USER}}
      run: ssh $SSH_USER@$SSH_HOST 'docker pull wbavishek/alita:latest'

    - name: Delete old Docker container
      env:
        SSH_HOST: ${{secrets.SSH_HOST}}
        SSH_USER: ${{secrets.SSH_USER}}
      run: ssh $SSH_USER@$SSH_HOST 'docker rm -f alita-container || true'

    - name: Run Docker container
      env:
        SSH_HOST: ${{secrets.SSH_HOST}}
        SSH_USER: ${{secrets.SSH_USER}}
      run: ssh $SSH_USER@$SSH_HOST 'docker run -d --name alita-container -v /home/ubuntu/deployments:/app wbavishek/alita'
