name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_URL: ${{secrets.DOCKER_URL}}
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login $DOCKER_URL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      env:
        DOCKER_URL: ${{secrets.DOCKER_URL}}
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: docker build -t $DOCKER_URL/$DOCKER_USERNAME/alita .
    - name: Push to Dockerhub
      env:
        DOCKER_URL: ${{secrets.DOCKER_URL}}
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: docker push $DOCKER_USERNAME/alita:latest
